controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
# api/config/routes.yaml
auth:
    path: api/login
    methods: ['POST']

api_refresh_token:
    path: /api/token/refresh
