version: '3'

services:
  nginx:
    container_name: nginx-sra
    image: nginx:alpine
    volumes:
      - ./docker/dev/nginx/server.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "8080:80"
  symfony:
    build:
      context: .
      dockerfile: ./docker/dev/alpine/Dockerfile
    image: projet_saline_royale_academy-symfony
    container_name: symfony-sra
    restart: on-failure
    environment:
      ELASTICSEARCH_USER: elastic
      ELASTICSEARCH_PASSWORD: ${ELASTIC_PASSWORD}
      ELASTICSEARCH_HOST: http://elasticsearch:9200/
      DATABASE_URL: mysql://$MYSQL_USER:$MYSQL_PASSWORD@db/$MYSQL_DATABASE?serverVersion=mariadb-$MYSQL_VERSION
    ports:
      - "1234:1234"
    volumes:
      - ./app/back:/var/www/symfony:delegated
      - ./docker/dev/nginx/symfony.conf:/etc/nginx/http.d/default.conf
    networks:
      - elasticsearch
      - web
      - acpSymfony

  node:
    build:
      context: .
      dockerfile: ./docker/dev/node/Dockerfile
    container_name: node-sra
    restart: on-failure
    volumes:
      - "./app/front:/app"
      - "/app/node_modules"
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
      - FAST_REFRESH=false
    networks:
      - web

  db:
    image: 'mariadb:10.11'
    restart: on-failure
    container_name: db-sra
    volumes:
      #      - './docker/bdd/my.cnf:/etc/mysql/conf.d/my.cnf:ro'
      - 'db-data-sra:/var/lib/mysql/:delegated'
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_PASSWORD
      MYSQL_DATABASE: $MYSQL_DATABASE
      MYSQL_USER: $MYSQL_USER
      MYSQL_PASSWORD: $MYSQL_PASSWORD
    ports:
      - "${MYSQL_PORT}:3306"
    networks:
      - acpSymfony

  elasticsearch:
    image: arm64v8/elasticsearch:8.7.1
    environment:
      ES_JAVA_OPTS: -Xms1g -Xmx1g
      discovery.type: single-node
      ELASTIC_PASSWORD : ${ELASTIC_PASSWORD}
      KIBANA_PASSWORD: ${KIBANA_PASSWORD}
#      USERNAME: ${USERNAME_ELASTIC}:elastica
#      PASSWORD: ${PASSWORD_ELASTIC}:elastica
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - /usr/share/elasticsearch/data
#      - ./docker/es/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - elasticsearch

  kibana:
    container_name: kibana-sra
    image: arm64v8/kibana:8.7.1
#    volumes:
#      -  ./docker/kibana/kibana.yml:/usr/share/kibana/config/kibana.yml
    environment:
      ELASTICSEARCH_USERNAME: kibana_system
      ELASTICSEARCH_PASSWORD: kibana_system
      ELASTICSEARCH_HOSTS: 'http://elasticsearch:9200'
    depends_on:
      - elasticsearch
    ports:
      - 5601:5601
    networks:
        - elasticsearch

  mailhog:
    image: mailhog/mailhog
    networks:
      - acpSymfony
    ports:
      - '8025:8025'
      - '1025:1025'
volumes:
  db-data-sra:
    driver: local
  elasticsearch-data:
    driver: local

networks:
  web:
    driver: bridge
  acpSymfony:
    driver: bridge
  elasticsearch:
    driver: bridge
