# Read the documentation: https://github.com/FriendsOfSymfony/FOSElasticaBundle/blob/master/doc/setup.md
fos_elastica:
  clients:
    default: {
      url: '%env(ELASTICSEARCH_URL)%',
      username: '%env(ELASTICSEARCH_USER)%',
      password: '%env(ELASTICSEARCH_PASSWORD)%'
    }
  indexes:
    app: null