monolog:
    channels:
        - deprecation # Deprecations are logged in the dedicated "deprecation" channel when it exists

when@dev:
    monolog:
        channels: [ "api" , "import"]
        handlers:
            main:
                type: stream
                path: "%kernel.logs_dir%/%kernel.environment%.log"
                level: debug
                channels: ["!event", "!sra" ]
            # uncomment to get logging in your browser
            # you may have to allow bigger header sizes in your Web server configuration
            #firephp:
            #    type: firephp
            #    level: info
            #chromephp:
            #    type: chromephp
            #    level: info
            console:
                type: console
                process_psr_3_messages: false
                channels: ["!event", "!doctrine", "!console", "!sra"]
            api:
                type: rotating_file
                path: "%kernel.logs_dir%/api/api.log"
                channels: [ "api" ]
                max_files: 30
            import:
                type: rotating_file
                path: "%kernel.logs_dir%/import/import.log"
                channels: [ "import" ]
                max_files: 30

when@test:
    monolog:
        handlers:
            main:
                type: fingers_crossed
                action_level: error
                handler: nested
                excluded_http_codes: [404, 405]
                channels: ["!event"]
            nested:
                type: stream
                path: "%kernel.logs_dir%/%kernel.environment%.log"
                level: debug

when@prod:
    monolog:
        handlers:
            main:
                type: fingers_crossed
                action_level: critical
                handler: nested
                excluded_http_codes: [403, 404, 405]
                buffer_size: 50 # How many messages should be saved? Prevent memory leaks
                channels: [ 'exception' ]
                environment: '%env(APP_ENV)%'
            nested:
                type: stream
                path: php://stderr
                level: debug
                formatter: monolog.formatter.json
            console:
                type: console
                process_psr_3_messages: false
                channels: ["!event", "!doctrine"]
                environment: '%env(APP_ENV)%'
            api:
                type: rotating_file
                path: "%kernel.logs_dir%/api/api.log"
                max_files: 30
