vich_uploader:
    db_driver: orm
    metadata:
        type: attribute

    mappings:
        media_object:
            uri_prefix: /files/media
            upload_destination: '%kernel.project_dir%/public/files/medias'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

        avatarFile:
            uri_prefix: files/avatars
            upload_destination: '%kernel.project_dir%/public/files/avatars'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

        badgeFile:
            uri_prefix: files/badge_images
            upload_destination: '%kernel.project_dir%/public/files/badge_images'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

        exercise_object:
            uri_prefix: /files/exercises
            upload_destination: '%kernel.project_dir%/public/files/exercises'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

        workAudioFile:
            uri_prefix: /files/work_audio
            upload_destination: '%kernel.project_dir%/public/files/work_audio'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

        workScoreFile:
            uri_prefix: /files/work_scores
            upload_destination: '%kernel.project_dir%/public/files/work_scores'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer