name: CI Production

on:
  workflow_dispatch:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
  release:
    types: created

jobs:
  Deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Pull latest images
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SERV }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.HOST }}
          script: |
            docker stop docker_symfony_1
            docker rm docker_symfony_1
            docker stop docker_nginx_1
            docker rm docker_nginx_1
            docker volume rm docker_symfony-sra
            docker pull ghcr.io/sebastien-jo/projet_saline_royale_academy-symfony:latest
            docker pull ghcr.io/sebastien-jo/projet_saline_royale_academy-nginx:latest
      - name: Up containers
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SERV }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.HOST }}
          script: |
            cd .docker
            docker-compose up -d
            docker cp docker_symfony_1:/var/www/react/public/build /tmp
            docker cp /tmp/build/ docker_symfony_1:/var/www/symfony/public/build
            rm -rf /tmp/build
      - name: Run DB migrations
        id: migration
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SERV }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.HOST }}
          script: |
            docker exec docker_symfony_1 bin/console doctrine:migrations:migrate --no-interaction
      - name: Dump env
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SERV }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.HOST }}
          script: |
            docker exec docker_symfony_1 composer dump-env prod
      - name: Install packages for prod
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SERV }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.HOST }}
          script: |
            docker exec docker_symfony_1 composer install
      - name: Give right to right on /var
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SERV }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.HOST }}
          script: |
            docker exec docker_symfony_1 sh -c 'chown -Rf www-data: var/'
      - name: Generate JWT keypair
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SERV }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.HOST }}
          script: |
            docker exec docker_symfony_1 sh -c 'php bin/console lexik:jwt:generate-keypair'
            docker exec docker_symfony_1 sh -c 'setfacl -R -m u:www-data:rX -m u:"$(whoami)":rwX config/jwt'
            docker exec docker_symfony_1 sh -c' setfacl -dR -m u:www-data:rX -m u:"$(whoami)":rwX config/jwt'
