name: TAG RELEASE

on:
  workflow_dispatch:

env:
  NODE_VERSION: 16

jobs:

  tag-release:
    name: Github release
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/dev'
    outputs:
      released_version: ${{ steps.release.outputs.version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        #Need be the same version as the docker-compose.yaml
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Get yarn cache directory path
        shell: bash
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - uses: actions/cache@v2
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Install yarn dependencies
        shell: bash
        run: yarn install

      - name: Release
        id: release
        env:
          GITHUB_TOKEN: ${{ github.token}}
        run: |
          yarn semantic-release
          echo "::set-output name=version::$([ -f version ] && sed 's/v//' version || echo)"
